# Use the file format compatible with Docker Compose 3.8
version: "2.7.0"

# Each thing that Docker Compose runs is referred to as
# a "service".
services:
  web:
    # The root directory from which we're building.
    build: .

    # This makes it so any code changes inside the project
    # directory get synced with Docker. Without this line,
    # we'd have to restart the container every time we
    # changed a file.
    volumes:
      - .:/code:cached

    # The command to be run when we run "docker-compose up".
    command: bash -c "rm -f tmp/pids/server.pid && npm start"

    # Expose port 3000.
    ports:
      - "4000:4000"

    # Specify that this container depends on the other
    # container which we've called "database".
    # depends_on:

    # Specify the values of the environment variables
    # used in this container.
    # environment:
    #   RAILS_ENV: development

# Declare the volumes that our application uses.
volumes:
  db_data: